heat_template_version: 2013-05-23

description: Nase prvni sablona

resources:
  sit1:
    type: OS::Neutron::Net
    properties:
      name: stackSit1
  
  subnet1:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: sit1 }
      cidr: 192.168.10.0/24
      allocation_pools:
        - start: 192.168.10.100
          end: 192.168.10.200

  sitovy_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: sit1 }
      fixed_ips:
        - subnet_id: { get_resource: subnet1 }

  prvniVM:
    type: OS::Nova::Server
    properties:
      key_name: mujKlic
      image: cirros-0.3.4-x86_64
      flavor: m1.tiny
      networks:
        - port: { get_resource: sitovy_port }
